### ISSUE TITLE
Error in make

### ISSUE THREAD

**Issue by PedroLucas201441** [cejtok/playluaengine#1]
Im having A error when im Emulate the Game to Test:
make: *** No rule to make target `all'.  Stop.
Error: rawgame.elf could not be created       

How to fix?

**Comment by cejtok** [comment]
Hi, can you please send me a screenshot?

**Comment by PedroLucas201441** [comment]
![image](https://github.com/cejtok/playluaengine/assets/118313199/6dccc5e7-a91f-4c97-baec-e411d391581b)
its hard to view an texts because the recifty 11 but can view the error

**Comment by cejtok** [comment]
Hi, You should set the PS2 Mode, from menu

**Comment by PedroLucas201441** [comment]
i dont have ps2 ;\

**Comment by PedroLucas201441** [comment]
now its worked :)
